import localFont from "next/font/local";
import "./globals.css";
import Nav from "./components/Nav";
import Footer from "./components/Footer";
const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "WorkoutWiz",
  description: "Generated by create next app",
  favicon: "/me.png",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" data-theme="winter" className="bg-base-300">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-base-100 overflow-scroll`}
      >
        <div className="flex flex-col h-screen">
          <Nav />
          <main className="flex-1">{children}</main>
          <Footer />
        </div>
      </body>
    </html>
  );
}
